//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RehostingLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RehostingLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearCommand {
            get {
                return ResourceManager.GetString("ClearCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string ExecuteCommand {
            get {
                return ResourceManager.GetString("ExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string ExecuteSlowCommand {
            get {
                return ResourceManager.GetString("ExecuteSlowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow|*.xaml|Service|*.xamlx.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New activity.
        /// </summary>
        internal static string NewActivityCommand {
            get {
                return ResourceManager.GetString("NewActivityCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New service.
        /// </summary>
        internal static string NewServiceCommand {
            get {
                return ResourceManager.GetString("NewServiceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenCommand {
            get {
                return ResourceManager.GetString("OpenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as ....
        /// </summary>
        internal static string SaveAsCommand {
            get {
                return ResourceManager.GetString("SaveAsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveCommand {
            get {
                return ResourceManager.GetString("SaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopCommand {
            get {
                return ResourceManager.GetString("StopCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string ToolboxCollection {
            get {
                return ResourceManager.GetString("ToolboxCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Flow.
        /// </summary>
        internal static string ToolboxControlFlow {
            get {
                return ResourceManager.GetString("ToolboxControlFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Handling.
        /// </summary>
        internal static string ToolboxErrorHandling {
            get {
                return ResourceManager.GetString("ToolboxErrorHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart.
        /// </summary>
        internal static string ToolboxFlowchart {
            get {
                return ResourceManager.GetString("ToolboxFlowchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string ToolboxMessaging {
            get {
                return ResourceManager.GetString("ToolboxMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration.
        /// </summary>
        internal static string ToolboxMigration {
            get {
                return ResourceManager.GetString("ToolboxMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitives.
        /// </summary>
        internal static string ToolboxPrimitives {
            get {
                return ResourceManager.GetString("ToolboxPrimitives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        internal static string ToolboxRuntime {
            get {
                return ResourceManager.GetString("ToolboxRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine.
        /// </summary>
        internal static string ToolboxStateMachine {
            get {
                return ResourceManager.GetString("ToolboxStateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string ToolboxTransaction {
            get {
                return ResourceManager.GetString("ToolboxTransaction", resourceCulture);
            }
        }
    }
}
